import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  assertAllowedUrl,
  assertCatalogIntegrity,
  assertSourceEntryCount,
  commitCatalogSnapshot,
  fetchImageResource,
  fetchJsonResource,
  mapWithConcurrency,
  OPEN_DOTA_API_ORIGINS,
  STEAM_CDN_ORIGINS,
} from './syncUtils.mjs';
import { itemCatalog as previousItemCatalog } from '../src/data/itemCatalog.js';

const STEAM_CDN_SITE = 'https://cdn.steamstatic.com';
const OPEN_DOTA_ITEM_IDS_API = 'https://api.opendota.com/api/constants/item_ids';
const OPEN_DOTA_ITEMS_API = 'https://api.opendota.com/api/constants/items';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const outputFile = path.join(projectRoot, 'src', 'data', 'itemCatalog.js');
const iconDir = path.join(projectRoot, 'public', 'assets', 'items');
const DOWNLOAD_CONCURRENCY = 8;
const MIN_ITEM_ENTRIES = 300;
const MAX_SNAPSHOT_DROP_RATIO = 0.15;
const MAX_ASSET_DROP_RATIO = 0.2;

const sanitizeFileName = (value) => String(value).replace(/[^a-zA-Z0-9._-]/g, '_');
const toObject = (value) => (value && typeof value === 'object' && !Array.isArray(value) ? value : {});

const toSteamCdnUrl = (value) => {
  if (!value) {
    return '';
  }
  return assertAllowedUrl(
    new URL(value, STEAM_CDN_SITE),
    STEAM_CDN_ORIGINS,
    'item icon'
  ).toString();
};

const prettifyToken = (value) =>
  String(value ?? '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());

const resolveItemName = (detail, token) => {
  const objectDetail = toObject(detail);
  return objectDetail.dname || objectDetail.localized_name || objectDetail.name || prettifyToken(token);
};

const buildIdToTokenMap = (payload) => {
  const source = toObject(payload);
  const map = new Map();

  Object.entries(source).forEach(([key, value]) => {
    const idFromKey = Number.parseInt(key, 10);
    if (Number.isFinite(idFromKey) && idFromKey > 0) {
      map.set(idFromKey, String(value));
      return;
    }

    const idFromValue = Number.parseInt(String(value), 10);
    if (Number.isFinite(idFromValue) && idFromValue > 0) {
      map.set(idFromValue, String(key));
    }
  });

  return map;
};

const toIconFileName = (token, extension) => sanitizeFileName(`${token}${extension}`);

const downloadIcon = async (token, remoteUrl, targetDir) => {
  if (!remoteUrl) {
    return null;
  }

  const image = await fetchImageResource(remoteUrl, {
    allowedOrigins: STEAM_CDN_ORIGINS,
    label: `item ${token} icon`,
  });
  const fileName = toIconFileName(token, image.extension);
  const filePath = path.join(targetDir, fileName);
  await writeFile(filePath, image.buffer);

  return {
    localPath: `/assets/items/${fileName}`,
    sourceUrl: image.finalUrl,
  };
};

const buildCatalogContent = (catalog) => {
  const generatedAt = new Date().toISOString();
  const lines = [
    '// This file is generated by scripts/syncItems.mjs',
    `// Generated at: ${generatedAt}`,
    '// nameZh is null when the upstream source provides no verified Chinese name.',
    '',
    'export const itemCatalog = [',
    ...catalog.map((item) => `  ${JSON.stringify(item)},`),
    '];',
    '',
    'export const itemCatalogById = new Map(itemCatalog.filter((item) => Number.isFinite(item.id)).map((item) => [item.id, item]));',
    'export const itemCatalogByKey = new Map(itemCatalog.map((item) => [item.key, item]));',
    '',
  ];

  return lines.join('\n');
};

const run = async () => {
  await mkdir(path.dirname(iconDir), { recursive: true });
  const stagingDir = await mkdtemp(
    path.join(path.dirname(iconDir), '.items-sync-')
  );

  try {
    const [itemIdsPayload, itemsPayload] = await Promise.all([
      fetchJsonResource(OPEN_DOTA_ITEM_IDS_API, {
        allowedOrigins: OPEN_DOTA_API_ORIGINS,
        label: 'OpenDota item IDs',
      }),
      fetchJsonResource(OPEN_DOTA_ITEMS_API, {
        allowedOrigins: OPEN_DOTA_API_ORIGINS,
        label: 'OpenDota item definitions',
      }),
    ]);

    const idToToken = buildIdToTokenMap(itemIdsPayload);
    const itemDefs = toObject(itemsPayload);
    const minimumSourceEntries = Math.max(
      MIN_ITEM_ENTRIES,
      Math.ceil(previousItemCatalog.length * (1 - MAX_SNAPSHOT_DROP_RATIO))
    );
    assertSourceEntryCount(idToToken, {
      label: 'OpenDota item ID definitions',
      minEntries: minimumSourceEntries,
    });
    assertSourceEntryCount(itemDefs, {
      label: 'OpenDota item definitions',
      minEntries: minimumSourceEntries,
    });
    const tokenToId = new Map();
    idToToken.forEach((token, id) => {
      tokenToId.set(token, id);
    });

    const tokens = [
      ...new Set([...tokenToId.keys(), ...Object.keys(itemDefs)]),
    ].sort((a, b) => {
      const idA = tokenToId.get(a) ?? Number.MAX_SAFE_INTEGER;
      const idB = tokenToId.get(b) ?? Number.MAX_SAFE_INTEGER;
      if (idA !== idB) {
        return idA - idB;
      }
      return a.localeCompare(b);
    });

    const catalog = await mapWithConcurrency(
      tokens,
      DOWNLOAD_CONCURRENCY,
      async (token) => {
        const detail = toObject(itemDefs[token]);
        const id = tokenToId.get(token);
        const nameEn = resolveItemName(detail, token);
        const remoteUrl = toSteamCdnUrl(detail.img);
        let icon;
        try {
          icon = await downloadIcon(token, remoteUrl, stagingDir);
        } catch (error) {
          throw new Error(`Item ${token} icon failed: ${error.message}`, {
            cause: error,
          });
        }

        return {
          id: Number.isFinite(id) ? id : null,
          key: token,
          nameEn,
          // OpenDota's item constants currently expose English names only.
          // `null` explicitly tells the UI to fall back to `nameEn`.
          nameZh: null,
          icon: icon?.localPath ?? '',
          iconSource: icon?.sourceUrl ?? remoteUrl,
        };
      }
    );
    assertCatalogIntegrity(catalog, {
      label: 'item catalog',
      minEntries: MIN_ITEM_ENTRIES,
      allowMissingIds: true,
      minValidIds: minimumSourceEntries,
      assetField: 'icon',
      assetExpectedField: 'iconSource',
      minExpectedAssets: minimumSourceEntries,
      minAssetCoverage: 1,
      previousCatalog: previousItemCatalog,
      maxEntryDropRatio: MAX_SNAPSHOT_DROP_RATIO,
      maxValidIdDropRatio: MAX_SNAPSHOT_DROP_RATIO,
      maxAssetDropRatio: MAX_ASSET_DROP_RATIO,
    });

    await commitCatalogSnapshot({
      stagingDir,
      targetDir: iconDir,
      catalogFile: outputFile,
      catalogContent: buildCatalogContent(catalog),
    });
    console.log(
      `Saved ${catalog.length} items with concurrency ${DOWNLOAD_CONCURRENCY} to ${outputFile}`
    );
  } catch (error) {
    await rm(stagingDir, { recursive: true, force: true });
    if (error instanceof AggregateError) {
      error.errors.forEach((failure) => console.error(failure.message));
    }
    throw error;
  }
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
