import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const OPEN_DOTA_SITE = 'https://www.opendota.com';
const STEAM_CDN_SITE = 'https://cdn.steamstatic.com';
const OPEN_DOTA_HEROES_API = 'https://api.opendota.com/api/constants/heroes';
const DOTA2_HERO_LIST_API = 'https://www.dota2.com/datafeed/herolist?language=schinese';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const outputFile = path.join(projectRoot, 'src', 'data', 'heroCatalog.js');
const avatarDir = path.join(projectRoot, 'public', 'assets', 'heroes');

const sanitizeFileName = (value) => value.replace(/[^a-zA-Z0-9._-]/g, '_');

const toAbsoluteUrl = (value) => {
  if (!value) {
    return '';
  }
  return new URL(value, OPEN_DOTA_SITE).toString();
};

const toSteamCdnUrl = (value) => {
  if (!value) {
    return '';
  }
  return new URL(value, STEAM_CDN_SITE).toString();
};

const toHeroSlug = (hero) => {
  if (typeof hero?.name === 'string' && hero.name.startsWith('npc_dota_hero_')) {
    return hero.name.replace('npc_dota_hero_', '');
  }
  return String(hero?.id ?? 'unknown');
};

const toAvatarFileName = (hero) => {
  const source = new URL(toAbsoluteUrl(hero.img));
  const ext = path.extname(source.pathname) || '.png';
  return sanitizeFileName(`${toHeroSlug(hero)}${ext}`);
};

const fetchHeroes = async () => {
  const response = await fetch(OPEN_DOTA_HEROES_API);
  if (!response.ok) {
    throw new Error(`Failed to fetch heroes list, HTTP ${response.status}`);
  }
  const data = await response.json();
  if (Array.isArray(data)) {
    return data;
  }
  if (data && typeof data === 'object') {
    return Object.values(data);
  }
  return [];
};

const fetchHeroNames = async () => {
  const response = await fetch(DOTA2_HERO_LIST_API);
  if (!response.ok) {
    throw new Error(`Failed to fetch hero names, HTTP ${response.status}`);
  }

  const payload = await response.json();
  const heroes = payload?.result?.data?.heroes;
  if (!Array.isArray(heroes)) {
    return new Map();
  }

  return heroes.reduce((map, hero) => {
    if (hero?.id == null) {
      return map;
    }

    map.set(hero.id, {
      nameZh: hero.name_loc ?? '',
      nameEn: hero.name_english_loc ?? '',
    });
    return map;
  }, new Map());
};

const downloadAvatar = async (hero) => {
  const remoteUrl = toSteamCdnUrl(hero.img);
  if (!remoteUrl) {
    return null;
  }

  const response = await fetch(remoteUrl);
  if (!response.ok) {
    throw new Error(`Failed to download avatar for hero ${hero.id}, HTTP ${response.status}`);
  }

  const fileName = toAvatarFileName(hero);
  const filePath = path.join(avatarDir, fileName);
  const buffer = Buffer.from(await response.arrayBuffer());
  await writeFile(filePath, buffer);

  return {
    localPath: `/assets/heroes/${fileName}`,
    sourceUrl: remoteUrl,
  };
};

const writeCatalog = async (catalog) => {
  const generatedAt = new Date().toISOString();
  const lines = [
    '// This file is generated by scripts/syncHeroes.mjs',
    `// Generated at: ${generatedAt}`,
    '',
    'export const heroCatalog = [',
    ...catalog.map((hero) => `  ${JSON.stringify(hero)},`),
    '];',
    '',
    'export const heroCatalogById = new Map(heroCatalog.map((hero) => [hero.id, hero]));',
    '',
  ];

  await writeFile(outputFile, lines.join('\n'));
};

const run = async () => {
  await mkdir(avatarDir, { recursive: true });
  const [heroes, heroNames] = await Promise.all([fetchHeroes(), fetchHeroNames()]);
  const sortedHeroes = [...heroes].sort((a, b) => (a.id ?? 0) - (b.id ?? 0));
  const catalog = [];

  for (const hero of sortedHeroes) {
    if (hero?.id == null) {
      continue;
    }

    const avatar = await downloadAvatar(hero);
    const localizedNames = heroNames.get(hero.id);
    const nameEn = localizedNames?.nameEn || hero.localized_name || `Hero #${hero.id}`;
    const nameZh = localizedNames?.nameZh || nameEn;

    catalog.push({
      id: hero.id,
      key: toHeroSlug(hero),
      nameEn,
      nameZh,
      avatar: avatar?.localPath ?? '',
      avatarSource: avatar?.sourceUrl ?? '',
    });
  }

  await writeCatalog(catalog);
  console.log(`Saved ${catalog.length} heroes to ${outputFile}`);
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
