import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  assertAllowedUrl,
  assertCatalogIntegrity,
  assertSourceEntryCount,
  commitCatalogSnapshot,
  DOTA2_DATA_ORIGINS,
  fetchImageResource,
  fetchJsonResource,
  mapWithConcurrency,
  OPEN_DOTA_API_ORIGINS,
  STEAM_CDN_ORIGINS,
} from './syncUtils.mjs';
import { heroCatalog as previousHeroCatalog } from '../src/data/heroCatalog.js';

const STEAM_CDN_SITE = 'https://cdn.steamstatic.com';
const OPEN_DOTA_HEROES_API = 'https://api.opendota.com/api/constants/heroes';
const DOTA2_HERO_LIST_API = 'https://www.dota2.com/datafeed/herolist?language=schinese';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const outputFile = path.join(projectRoot, 'src', 'data', 'heroCatalog.js');
const avatarDir = path.join(projectRoot, 'public', 'assets', 'heroes');
const DOWNLOAD_CONCURRENCY = 8;
const MIN_HERO_ENTRIES = 100;
const MAX_SNAPSHOT_DROP_RATIO = 0.1;

const sanitizeFileName = (value) => value.replace(/[^a-zA-Z0-9._-]/g, '_');

const toSteamCdnUrl = (value) => {
  if (!value) {
    return '';
  }
  return assertAllowedUrl(
    new URL(value, STEAM_CDN_SITE),
    STEAM_CDN_ORIGINS,
    'hero avatar'
  ).toString();
};

const toHeroSlug = (hero) => {
  if (typeof hero?.name === 'string' && hero.name.startsWith('npc_dota_hero_')) {
    return hero.name.replace('npc_dota_hero_', '');
  }
  return String(hero?.id ?? 'unknown');
};

const toAvatarFileName = (hero, extension) =>
  sanitizeFileName(`${toHeroSlug(hero)}${extension}`);

const fetchHeroes = async () => {
  const data = await fetchJsonResource(OPEN_DOTA_HEROES_API, {
    allowedOrigins: OPEN_DOTA_API_ORIGINS,
    label: 'OpenDota heroes list',
  });
  if (Array.isArray(data)) {
    return data;
  }
  if (data && typeof data === 'object') {
    return Object.values(data);
  }
  return [];
};

const fetchHeroNames = async () => {
  const payload = await fetchJsonResource(DOTA2_HERO_LIST_API, {
    allowedOrigins: DOTA2_DATA_ORIGINS,
    label: 'Dota 2 localized hero names',
  });
  const heroes = payload?.result?.data?.heroes;
  if (!Array.isArray(heroes)) {
    return new Map();
  }

  return heroes.reduce((map, hero) => {
    if (hero?.id == null) {
      return map;
    }

    map.set(hero.id, {
      nameZh: hero.name_loc ?? '',
      nameEn: hero.name_english_loc ?? '',
    });
    return map;
  }, new Map());
};

const downloadAvatar = async (hero, targetDir) => {
  const remoteUrl = toSteamCdnUrl(hero.img);
  if (!remoteUrl) {
    return null;
  }

  const image = await fetchImageResource(remoteUrl, {
    allowedOrigins: STEAM_CDN_ORIGINS,
    label: `hero ${hero.id} avatar`,
  });
  const fileName = toAvatarFileName(hero, image.extension);
  const filePath = path.join(targetDir, fileName);
  await writeFile(filePath, image.buffer);

  return {
    localPath: `/assets/heroes/${fileName}`,
    sourceUrl: image.finalUrl,
  };
};

const buildCatalogContent = (catalog) => {
  const generatedAt = new Date().toISOString();
  const lines = [
    '// This file is generated by scripts/syncHeroes.mjs',
    `// Generated at: ${generatedAt}`,
    '',
    'export const heroCatalog = [',
    ...catalog.map((hero) => `  ${JSON.stringify(hero)},`),
    '];',
    '',
    'export const heroCatalogById = new Map(heroCatalog.map((hero) => [hero.id, hero]));',
    '',
  ];

  return lines.join('\n');
};

const run = async () => {
  await mkdir(path.dirname(avatarDir), { recursive: true });
  const stagingDir = await mkdtemp(
    path.join(path.dirname(avatarDir), '.heroes-sync-')
  );
  try {
    const [heroes, heroNames] = await Promise.all([
      fetchHeroes(),
      fetchHeroNames(),
    ]);
    assertSourceEntryCount(heroes, {
      label: 'OpenDota hero definitions',
      minEntries: MIN_HERO_ENTRIES,
    });
    const localizedHeroNames = [...heroNames.values()].filter(
      (entry) => typeof entry?.nameZh === 'string' && entry.nameZh.trim()
    );
    assertSourceEntryCount(localizedHeroNames, {
      label: 'Dota 2 localized hero names',
      minEntries: Math.max(
        MIN_HERO_ENTRIES,
        Math.ceil(previousHeroCatalog.length * (1 - MAX_SNAPSHOT_DROP_RATIO))
      ),
    });
    const sortedHeroes = [...heroes].sort((a, b) => (a.id ?? 0) - (b.id ?? 0));
    const eligibleHeroes = sortedHeroes.filter((hero) => hero?.id != null);
    const catalog = await mapWithConcurrency(
      eligibleHeroes,
      DOWNLOAD_CONCURRENCY,
      async (hero) => {
        let avatar;
        try {
          avatar = await downloadAvatar(hero, stagingDir);
        } catch (error) {
          throw new Error(
            `Hero ${hero.id} (${toHeroSlug(hero)}) avatar failed: ${error.message}`,
            { cause: error }
          );
        }
        const localizedNames = heroNames.get(hero.id);
        const nameEn =
          localizedNames?.nameEn || hero.localized_name || `Hero #${hero.id}`;
        const nameZh = localizedNames?.nameZh || nameEn;

        return {
          id: hero.id,
          key: toHeroSlug(hero),
          nameEn,
          nameZh,
          primaryAttr: hero.primary_attr ?? '',
          attackType: hero.attack_type ?? '',
          roles: Array.isArray(hero.roles) ? hero.roles : [],
          baseStr: Number.isFinite(Number(hero.base_str)) ? Number(hero.base_str) : null,
          strGain: Number.isFinite(Number(hero.str_gain)) ? Number(hero.str_gain) : null,
          baseAgi: Number.isFinite(Number(hero.base_agi)) ? Number(hero.base_agi) : null,
          agiGain: Number.isFinite(Number(hero.agi_gain)) ? Number(hero.agi_gain) : null,
          baseInt: Number.isFinite(Number(hero.base_int)) ? Number(hero.base_int) : null,
          intGain: Number.isFinite(Number(hero.int_gain)) ? Number(hero.int_gain) : null,
          attackRange: Number.isFinite(Number(hero.attack_range)) ? Number(hero.attack_range) : null,
          moveSpeed: Number.isFinite(Number(hero.move_speed)) ? Number(hero.move_speed) : null,
          avatar: avatar?.localPath ?? '',
          avatarSource: avatar?.sourceUrl ?? '',
        };
      }
    );
    assertCatalogIntegrity(catalog, {
      label: 'hero catalog',
      minEntries: MIN_HERO_ENTRIES,
      minValidIds: MIN_HERO_ENTRIES,
      assetField: 'avatar',
      minAssetCoverage: 0.95,
      previousCatalog: previousHeroCatalog,
      maxEntryDropRatio: MAX_SNAPSHOT_DROP_RATIO,
      maxValidIdDropRatio: MAX_SNAPSHOT_DROP_RATIO,
      maxAssetDropRatio: MAX_SNAPSHOT_DROP_RATIO,
    });

    await commitCatalogSnapshot({
      stagingDir,
      targetDir: avatarDir,
      catalogFile: outputFile,
      catalogContent: buildCatalogContent(catalog),
    });
    console.log(
      `Saved ${catalog.length} heroes with concurrency ${DOWNLOAD_CONCURRENCY} to ${outputFile}`
    );
  } catch (error) {
    await rm(stagingDir, { recursive: true, force: true });
    if (error instanceof AggregateError) {
      error.errors.forEach((failure) => console.error(failure.message));
    }
    throw error;
  }
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
