import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const OPEN_DOTA_SITE = 'https://www.opendota.com';
const STEAM_CDN_SITE = 'https://cdn.steamstatic.com';
const OPEN_DOTA_ITEM_IDS_API = 'https://api.opendota.com/api/constants/item_ids';
const OPEN_DOTA_ITEMS_API = 'https://api.opendota.com/api/constants/items';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const outputFile = path.join(projectRoot, 'src', 'data', 'itemCatalog.js');
const iconDir = path.join(projectRoot, 'public', 'assets', 'items');

const sanitizeFileName = (value) => String(value).replace(/[^a-zA-Z0-9._-]/g, '_');
const toObject = (value) => (value && typeof value === 'object' && !Array.isArray(value) ? value : {});

const toAbsoluteUrl = (value) => {
  if (!value) {
    return '';
  }
  return new URL(value, OPEN_DOTA_SITE).toString();
};

const toSteamCdnUrl = (value) => {
  if (!value) {
    return '';
  }
  return new URL(value, STEAM_CDN_SITE).toString();
};

const prettifyToken = (value) =>
  String(value ?? '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());

const resolveItemName = (detail, token) => {
  const objectDetail = toObject(detail);
  return objectDetail.dname || objectDetail.localized_name || objectDetail.name || prettifyToken(token);
};

const buildIdToTokenMap = (payload) => {
  const source = toObject(payload);
  const map = new Map();

  Object.entries(source).forEach(([key, value]) => {
    const idFromKey = Number.parseInt(key, 10);
    if (Number.isFinite(idFromKey) && idFromKey > 0) {
      map.set(idFromKey, String(value));
      return;
    }

    const idFromValue = Number.parseInt(String(value), 10);
    if (Number.isFinite(idFromValue) && idFromValue > 0) {
      map.set(idFromValue, String(key));
    }
  });

  return map;
};

const fetchJson = async (url) => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}, HTTP ${response.status}`);
  }
  return response.json();
};

const toIconFileName = (token, iconUrl) => {
  const source = new URL(iconUrl);
  const ext = path.extname(source.pathname) || '.png';
  return sanitizeFileName(`${token}${ext}`);
};

const downloadIcon = async (token, detail) => {
  const iconSource = toObject(detail).img;
  const remoteUrl = toSteamCdnUrl(iconSource);
  if (!remoteUrl) {
    return null;
  }

  const response = await fetch(remoteUrl);
  if (!response.ok) {
    throw new Error(`Failed to download icon for item ${token}, HTTP ${response.status}`);
  }

  const fileName = toIconFileName(token, remoteUrl);
  const filePath = path.join(iconDir, fileName);
  const buffer = Buffer.from(await response.arrayBuffer());
  await writeFile(filePath, buffer);

  return {
    localPath: `/assets/items/${fileName}`,
    sourceUrl: remoteUrl,
  };
};

const writeCatalog = async (catalog) => {
  const generatedAt = new Date().toISOString();
  const lines = [
    '// This file is generated by scripts/syncItems.mjs',
    `// Generated at: ${generatedAt}`,
    '',
    'export const itemCatalog = [',
    ...catalog.map((item) => `  ${JSON.stringify(item)},`),
    '];',
    '',
    'export const itemCatalogById = new Map(itemCatalog.filter((item) => Number.isFinite(item.id)).map((item) => [item.id, item]));',
    'export const itemCatalogByKey = new Map(itemCatalog.map((item) => [item.key, item]));',
    '',
  ];

  await writeFile(outputFile, lines.join('\n'));
};

const run = async () => {
  await mkdir(iconDir, { recursive: true });

  const [itemIdsPayload, itemsPayload] = await Promise.all([
    fetchJson(OPEN_DOTA_ITEM_IDS_API),
    fetchJson(OPEN_DOTA_ITEMS_API),
  ]);

  const idToToken = buildIdToTokenMap(itemIdsPayload);
  const itemDefs = toObject(itemsPayload);
  const tokenToId = new Map();
  idToToken.forEach((token, id) => {
    tokenToId.set(token, id);
  });

  const tokens = [...new Set([...tokenToId.keys(), ...Object.keys(itemDefs)])].sort((a, b) => {
    const idA = tokenToId.get(a) ?? Number.MAX_SAFE_INTEGER;
    const idB = tokenToId.get(b) ?? Number.MAX_SAFE_INTEGER;
    if (idA !== idB) {
      return idA - idB;
    }
    return a.localeCompare(b);
  });

  const catalog = [];

  for (const token of tokens) {
    const detail = toObject(itemDefs[token]);
    const id = tokenToId.get(token);
    const nameEn = resolveItemName(detail, token);
    const icon = await downloadIcon(token, detail).catch(() => null);

    catalog.push({
      id: Number.isFinite(id) ? id : null,
      key: token,
      nameEn,
      nameZh: nameEn,
      icon: icon?.localPath ?? '',
      iconSource: icon?.sourceUrl ?? toAbsoluteUrl(detail.img),
    });
  }

  await writeCatalog(catalog);
  console.log(`Saved ${catalog.length} items to ${outputFile}`);
};

run().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
